import {
  LucideArchive,
  LucideArrowDownRight,
  LucideArrowLeft,
  LucideArrowRight,
  LucideArrowUpRight,
  LucideAlertCircle,
  LucideBanknote,
  LucideBarChart3,
  LucideBell,
  LucideBellRing,
  LucideBookOpen,
  LucideCalendar,
  LucideCalendarCheck,
  LucideCalendarDays,
  LucideCalendarPlus,
  LucideCamera,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideChevronsLeft,
  LucideChevronsRight,
  LucideCircle,
  LucideCircleCheck,
  LucideCirclePlus,
  LucideClock,
  LucideCoins,
  LucideCreditCard,
  LucideDumbbell,
  LucideDownload,
  LucideExternalLink,
  LucideEye,
  LucideEyeOff,
  LucideFilter,
  LucideFlag,
  LucideFlame,
  LucideGauge,
  LucideGift,
  LucideGlobe,
  LucideInfo,
  LucideInbox,
  LucideKeyRound,
  LucideLanguages,
  LucideLayoutDashboard,
  LucideLineChart,
  LucideListTodo,
  LucideLoaderCircle,
  LucideLock,
  LucideLogIn,
  LucideLogOut,
  LucideMail,
  LucideMenu,
  LucideMinus,
  LucideMoon,
  LucideMoreHorizontal,
  LucideMoreVertical,
  LucideNotebookPen,
  LucidePackage,
  LucidePalette,
  LucidePanelLeft,
  LucidePause,
  LucidePencil,
  LucidePieChart,
  LucidePiggyBank,
  LucidePin,
  LucidePlay,
  LucidePlus,
  LucideReceipt,
  LucideRefreshCw,
  LucideRepeat,
  LucideRotateCcw,
  LucideSearch,
  LucideSettings,
  LucideShoppingBag,
  LucideShoppingBasket,
  LucideSmartphone,
  LucideSparkles,
  LucideStar,
  LucideStickyNote,
  LucideSun,
  LucideTarget,
  LucideTimer,
  LucideTrash2,
  LucideTrendingDown,
  LucideTrendingUp,
  LucideTrophy,
  LucideUser,
  LucideUserPlus,
  LucideUserRound,
  LucideUtensils,
  LucideWallet,
  LucideX,
  LucideZap,
  type LucideIconData,
} from '@lucide/angular';

export const ICONS: Record<string, LucideIconData> = {
  'layout-dashboard': LucideLayoutDashboard.icon,
  'list-todo': LucideListTodo.icon,
  'circle-check': LucideCircleCheck.icon,
  check: LucideCheck.icon,
  circle: LucideCircle.icon,
  'circle-plus': LucideCirclePlus.icon,
  wallet: LucideWallet.icon,
  gift: LucideGift.icon,
  'shopping-basket': LucideShoppingBasket.icon,
  'shopping-bag': LucideShoppingBag.icon,
  'smartphone': LucideSmartphone.icon,
  calendar: LucideCalendar.icon,
  'calendar-days': LucideCalendarDays.icon,
  'calendar-check': LucideCalendarCheck.icon,
  'calendar-plus': LucideCalendarPlus.icon,
  target: LucideTarget.icon,
  flame: LucideFlame.icon,
  'sticky-note': LucideStickyNote.icon,
  timer: LucideTimer.icon,
  'bar-chart-3': LucideBarChart3.icon,
  'line-chart': LucideLineChart.icon,
  'pie-chart': LucidePieChart.icon,
  settings: LucideSettings.icon,
  user: LucideUser.icon,
  'user-round': LucideUserRound.icon,
  'user-plus': LucideUserPlus.icon,
  plus: LucidePlus.icon,
  minus: LucideMinus.icon,
  search: LucideSearch.icon,
  bell: LucideBell.icon,
  'bell-ring': LucideBellRing.icon,
  menu: LucideMenu.icon,
  'panel-left': LucidePanelLeft.icon,
  'chevron-left': LucideChevronLeft.icon,
  'chevron-right': LucideChevronRight.icon,
  'chevron-down': LucideChevronDown.icon,
  'chevron-up': LucideChevronUp.icon,
  'chevrons-left': LucideChevronsLeft.icon,
  'chevrons-right': LucideChevronsRight.icon,
  'more-horizontal': LucideMoreHorizontal.icon,
  'more-vertical': LucideMoreVertical.icon,
  pencil: LucidePencil.icon,
  'trash-2': LucideTrash2.icon,
  archive: LucideArchive.icon,
  filter: LucideFilter.icon,
  clock: LucideClock.icon,
  flag: LucideFlag.icon,
  pin: LucidePin.icon,
  'arrow-up-right': LucideArrowUpRight.icon,
  'arrow-down-right': LucideArrowDownRight.icon,
  'arrow-right': LucideArrowRight.icon,
  'arrow-left': LucideArrowLeft.icon,
  'trending-up': LucideTrendingUp.icon,
  'trending-down': LucideTrendingDown.icon,
  'piggy-bank': LucidePiggyBank.icon,
  'credit-card': LucideCreditCard.icon,
  banknote: LucideBanknote.icon,
  receipt: LucideReceipt.icon,
  'refresh-cw': LucideRefreshCw.icon,
  star: LucideStar.icon,
  trophy: LucideTrophy.icon,
  repeat: LucideRepeat.icon,
  zap: LucideZap.icon,
  play: LucidePlay.icon,
  pause: LucidePause.icon,
  'rotate-ccw': LucideRotateCcw.icon,
  sun: LucideSun.icon,
  moon: LucideMoon.icon,
  'log-out': LucideLogOut.icon,
  'log-in': LucideLogIn.icon,
  x: LucideX.icon,
  'alert-circle': LucideAlertCircle.icon,
  info: LucideInfo.icon,
  inbox: LucideInbox.icon,
  sparkles: LucideSparkles.icon,
  'loader-circle': LucideLoaderCircle.icon,
  eye: LucideEye.icon,
  'eye-off': LucideEyeOff.icon,
  'external-link': LucideExternalLink.icon,
  'key-round': LucideKeyRound.icon,
  lock: LucideLock.icon,
  mail: LucideMail.icon,
  camera: LucideCamera.icon,
  palette: LucidePalette.icon,
  globe: LucideGlobe.icon,
  languages: LucideLanguages.icon,
  gauge: LucideGauge.icon,
  coins: LucideCoins.icon,
  'notebook-pen': LucideNotebookPen.icon,
  package: LucidePackage.icon,
  utensils: LucideUtensils.icon,
  dumbbell: LucideDumbbell.icon,
  download: LucideDownload.icon,
  'book-open': LucideBookOpen.icon,
};
